### ISSUE TITLE
Publish wheels?

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-slack#104]
I was wondering if it would be possible to publish wheels for this project? Typically wheels install faster and avoid consumers needing to run `setup.py` on their own machines.
I'm not aware of a reason for this project not to build wheels, yet PyPI doesn't appear to have them for recent releases.

**Comment by lamby** [comment]
Sure - I had only been calling `sdist` before. Let me upload a new version now with a wheel as a testrun...

**Comment by lamby** [comment]
`django_slack-5.16.2-py3-none-any.whl` uploaded. :)
