### ISSUE TITLE
adding `slack_admins` to `django.request`

### ISSUE THREAD

**Issue by trinhdh** [lamby/django-slack#106]
Hi,
Thanks for the great library. I have made it work follow this example: https://django-slack.readthedocs.io/
However, when i am trying to add `slack_admins` to `django.request`. the `slack_admins` is not working any more. I am not sure if its something wrong with my code or with the library. Just checking here to see if this is the case. Thanks

I also post my question here: https://stackoverflow.com/questions/68475459/django-filter-logging-to-slack-channel

**Comment by lamby** [comment]
Thanks. Will close this help request given I am now aware of the SO thread. Obviously re-open this if there is a definite bug in django-slack! :)
