### ISSUE TITLE
[Q] Release docs / notes

### ISSUE THREAD

**Issue by leikoilja** [lamby/django-slack#111]
Hey, @lamby. 

Great project, thanks for releasing it open source. Could you please point me where to find release notes or change logs to be able to follow the progression of the package for safer update on our system?

**Comment by lamby** [comment]
I am not in the habit of writing release notes for this project, sorry, but the git commit history should be a relatively readable alternative. The project does use SemVer, so that should denote whenever there are backwards-incompatible changes. :+1:

**Comment by leikoilja** [comment]
oh, that's understandable, thank you, @lamby. 
If interested check our [release-drafter](https://github.com/release-drafter/release-drafter), it's easy to set up and would do most of the heavy lifting by extracting notes and descriptions from PRs and putting it into release drafts which can be later published/release easily.
