### ISSUE TITLE
Django 3.2 does not see templates

### ISSUE THREAD

**Issue by lorandvarga** [lamby/django-slack#113]
The app is seen but the templates are not.
I've set all the settings correctly.
After debugging for a while I suspect this is related to setup.py not having the zip_safe set to False. From what I see setuptools determines that the library is zip_safe (True) and installs it as an egg. When django searches for the templates it can't search the egg (because it's a zip) and fails to find it.

Solution:
add zip_safe=False to setup.py file.

**Comment by lamby** [comment]
Great, thanks!
