### ISSUE TITLE
Installation exception (Python 3)

### ISSUE THREAD

**Issue by Eraldo** [lamby/django-slack#18]
# Context

Name | Version
---|---
Os | OS X 10.11.1 
Allauth | 0.23.0.final.0
Crispy_Forms | 1.5.2
Debug Toolbar | 1.4
Django | 1.8.5
Django_Extensions | 1.5.7
Message queue | 1.0.0
Python | 3.4.1

# What I did
`$ pip install django-slack`
Added `INSTALLED_APPS += ('django_slack', )` to my settings.
`$ ./manage.py runserver`

# Traceback
```python
...
  File "/Users/eraldo/.virtualenvs/colegend/lib/python3.4/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/Users/eraldo/.virtualenvs/colegend/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

Process finished with exit code 1
```

# Debugging

To find out what went wrong, I did:
```python
import django_slack
```
 
That got me this trace:
```python
  File "/Users/eraldo/.virtualenvs/colegend/lib/python3.4/site-packages/django_slack/backends.py", line 3, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

Some research later I found the suggested fix:
http://stackoverflow.com/questions/2792650/python3-error-import-error-no-module-name-urllib

# Action

I would love your app to work with python 3.
I am not used to doing things like pull requests.

So Chris, how shall we proceed? :D 

Friendly greetings from Berlin..
*Eraldo*

**Comment by Eraldo** [comment]
This seems to be related to: #12

**Comment by Eraldo** [comment]
I created a pull request which solves this issue: #19

**Comment by lamby** [comment]
Fixed on master,
