### ISSUE TITLE
If you specify SLACK_ENDPOINT_URL, it should be allowed to have SLACK_CHANNEL = None.

### ISSUE THREAD

**Issue by fero10101** [lamby/django-slack#27]
I want to send a message to private channel via webhook SLACK_ENDPOINT_URL. I have a endpoint url for webhook.
I get an error because i do not specified SLACK_CHANNEL. But if I specify SLACK_CHANNEL I do not receive a message.

https://github.com/lamby/django-slack/blob/master/django_slack/api.py#L58

**Comment by lamby** [comment]
Thanks @fero10101  :)

**Comment by lamby** [comment]
uploaded to pypi as django-slack-4.2.4
