### ISSUE TITLE
Indentation error in 4.2.4

### ISSUE THREAD

**Issue by nedjam** [lamby/django-slack#28]
There seems to have been an indentation error introduced in the latest release an hour ago. See below:

```
  File "/usr/local/lib/python2.7/site-packages/django_slack/api.py", line 86
    "URL is not specified"
    ^
IndentationError: unexpected indent
```

**Comment by lamby** [comment]
That'll teach me to test and then make further changes.. uploaded as 4.2.5.  Thanks!

**Comment by nedjam** [comment]
Thanks for the quick fix! (And django-slack - amazingly useful).

**Comment by lamby** [comment]
@nedjam No problem at all
