### ISSUE TITLE
No PyPi release of django-slack library.

### ISSUE THREAD

**Issue by avelis** [lamby/django-slack#3]
Is there an ability to install this library via Python's default package manager (pip)?

I know I can install via source but it's a little less than ideal.

**Comment by green-latte** [comment]
I uploaded PyPi, then you can install via pip.
@lamby sorry for my uploading arbitrarily, because we should install your django-slack from aws-eb automatically with requirements.txt. If you've got a PyPi account, I'll transfer my PyPi package to you.

**Comment by lamby** [comment]
@green-latte No problem. Please transfer to the "lamby" account on PyPI.

**Comment by green-latte** [comment]
@lamby I added you as owner on PyPI.

**Comment by lamby** [comment]
Thanks all - closing this issue. :)
