### ISSUE TITLE
RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.

### ISSUE THREAD

**Issue by clokep** [lamby/django-slack#30]
Thanks for the awesome package! I noticed a deprecation warning while running this under Django 1.9.2.

> Feb  9 19:39:41 dev supervisord: gunicorn /venv/local/lib/python2.7/site-packages/django_slack/api.py:63: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.

Seems to be related to manually creating a `Context` and feeding it into [`render_to_string`](https://docs.djangoproject.com/en/1.9/topics/templates/#django.template.loader.render_to_string)?

**Comment by lamby** [comment]
I also see this and have been meaning to fix it for a while.. but thanks for the report and the nudge P)
