### ISSUE TITLE
Overriding endpoint_url per message is not working.

### ISSUE THREAD

**Issue by fero10101** [lamby/django-slack#32]
Feature: 
You can override on a per-message level by specifying a {% block endpoint_url %}{% endblock %} in your message template.

is not working.

in my template i have a block with incoming webhook url:
{% block endpoint_url %}
https://hooks.slack.com/services/xxxxx/xxxx/xxxxx
{% endblock %}

settings:
SLACK_CHANNEL = ''
SLACK_USERNAME = 'test'

error:
  File "/Users/xx/.virtualenvs/xx-web/lib/python2.7/site-packages/django_slack/api.py", line 97, in slack_message
    raise ValueError("channel parameter is required if custom " \
ValueError: channel parameter is required if custom endpoint URL is not specified

**Comment by fero10101** [comment]
Work if render is True

        'endpoint_url': {
            'default': app_settings.ENDPOINT_URL,
            'render': False,

**Comment by lamby** [comment]
Thanks!
