### ISSUE TITLE
Over-aggressive HTML entity escaping

### ISSUE THREAD

**Issue by clokep** [lamby/django-slack#33]
By default, `django-slack` escapes all HTML entites (well really Django templates do, but that's essentially the same thing here). This is [documented](https://django-slack.readthedocs.org/#usage), but the documentation should probably be expanded to say that [only `<`, `>` and `&` should be escaped](https://api.slack.com/docs/formatting#how_to_escape_characters). In fact the slack documentation says NOT to escape other characters:

> That's it. **Don't HTML entity-encode the entire message.** Of course, when you send your message using URL-encoding, you'll still need to URL encode the ampersand.

Specifically, I was running into an issue where I had a message with a single quote (`'`) that was showing up as an entity in slack (`&#39;`). The examples in the documentation show usage of the [`safe` templatetag](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#safe), but it was not clear to me why this was happening. Calling this out explicitly would be nice.

I'm unsure if this is a documentation or a code issue, but the work around is to pass variables through the `safe` templatetag or disable `autoescape`.

**Comment by lamby** [comment]
Thanks for raising this. I'll have a ponder, but I think I can pretty much rule out disabling ``autoescape

**Comment by clokep** [comment]
I agree! Maybe we can improve the documentation around it? It was completely unexpected to me.

**Comment by lamby** [comment]
> Maybe we can improve the documentation around it? It was completely unexpected to me.

Lets go with that. Could you prepare a PR? Very very happy to merge..

**Comment by clokep** [comment]
@lamby I talked this over with a co-worker and I think a reasonable solution might be to make a template-tag which escapes the 3 characters Slack wants escaped (`<`, `>`, `&`) and then marks the string as `safe` such that Django will not try to escape `'` and `"`. Does that seem like a reasonable compromise?

Note that actually marking a string as `safe` will let through [dangerous links](https://api.slack.com/docs/formatting#linking_to_urls) (e.g. pinging all users in a room, etc.).

You'd then do something like this in a template:
```jinja
{% extends django_slack %}
{% load slacksafe %}

{% block text %}
Message text here: {{ foo.bar|urlize }} {{ foo.user.get_full_name|slacksafe }}
{% endblock %}
```

**Comment by lamby** [comment]
> a template-tag which escapes the 3 characters Slack wants escaped

Oh, that's a neat idea. Fancy giving it a go?

I *think* we should be able to avoid the explicit ``{% load slacksafe %}`` given that we control the call to ``render_to_string``.

Would also prefer ``|escapeslack`` to mirror ``|escapejs``.

**Comment by clokep** [comment]
Sure I'll take a look at it.
