### ISSUE TITLE
ConsoleBackend should use a logger instead of print

### ISSUE THREAD

**Issue by clokep** [lamby/django-slack#34]
This way the output of the `ConsoleBackend` won't show up if logging is disabled (e.g. I set `logging.disable(logging.CRITICAL)` for tests). Although it's likely faster to use the `DisabledBackend`...

**Comment by clokep** [comment]
Alternately, django seems to use streams: https://github.com/django/django/blob/master/django/core/mail/backends/console.py#L13

**Comment by lamby** [comment]
Streams just appear to be configurable print. :)  I think the solution here is:

 * Make ConsoleBackend copy the configurable steam
 * Add a LoggingBackend for your use-case

**Comment by clokep** [comment]
Thanks! 👍
