### ISSUE TITLE
Request: Support for richly-formatted messages via attachments.

### ISSUE THREAD

**Issue by avelis** [lamby/django-slack#4]
Observing the documentation on [chat.postMessage](https://api.slack.com/methods/chat.postMessage), there is the ability to create [richly-formatted messages via attachments](https://api.slack.com/docs/attachments).

I realize this adds to the complexity of the project but would really round out the feature-set and increase the utility of this library.

If I find time I will see what I could do to issue a pull-request. Having some unit-tests could help.

**Comment by lamby** [comment]
It would be a shame not to support that somehow. My gut feeling is that it would be easier to send these messages /outside/ of the templating system - ie. you pass a dict with all that stuff rather than making a ``.slack`` template. There just seems too many arguments to deal with for it to be sensible.

**Comment by avelis** [comment]
@lamby I agree. Perhaps the dictionary could be some form of structured keyword arguments. I think the challenge then would be argument enforcement when code is executed with input malformed `kwargs`.

hmm...

**Comment by lamby** [comment]
In the first instance, I'd probably not bother with much validation. We would never be able to catch it all anyway, so we can punt most of it off to Slack (who might change the validation at any moment anyway...)

**Comment by avelis** [comment]
@lamby I was finally able to test out #5 . I have determined that in whatever value you pass in via the attachments parameter that same value has to be encoded into a JSON string before being sent to Slack's chat.postMessage API.

e.g.
```
import json
...
if attachments:
    data['attachments'] = json.dumps(attachments)
...
```
This seems to make sense. The way I see it the, attachments key/value will send a JSON list containing a JSON dictionary. All other data values can be satisfied with just strings.

Before I make another pull request with this change, would it be sensible to ensure the `slack_message` method always JSON encodes the attachments value when present (as exampled above)?

**Comment by lamby** [comment]
> Should the JSON encoding of the attachments value fall on the developer outside of slack_message?

I think this would be a mistake - it's a Python method, the fact that JSON is used is a complete implementation detail that should be hidden as much as possible.

> ensure the slack_message method always JSON encodes the attachments value when present (as exampled above)?

This seems sensible - look forward to your PR.

**Comment by avelis** [comment]
@lamby Thanks again for all the PR merges. Would I need to make some documentation on this before a release could be made?

**Comment by lamby** [comment]
Some documenation would be excellent, yes. Especially with examples!

**Comment by lamby** [comment]
Can close this now.

**Comment by avelis** [comment]
:tada:
