### ISSUE TITLE
support for django versions lower then 1.8

### ISSUE THREAD

**Issue by OriHoch** [lamby/django-slack#42]
in the setup.py it says:
```python
install_requires=(
     'Django>=1.8.0',
```

Do you know of any specific problems with lower versions?

We got a large project using Django 1.6 unfortunately.. so I'll try to see if it works, but if you know of any specific problems it would be helpful

**Comment by OriHoch** [comment]
that's the project BTW: http://github.com/hasadna/Open-Knesset

**Comment by lamby** [comment]
No specific reason but 1.8 is minimum supported upstream and I don't have Infinite time, alas :) 

On Fri, 8 Apr 2016, at 07:03 AM, Ori Hoch wrote:
> in the setup.py it says:
> ```python
> install_requires=(
>      'Django>=1.8.0',
> ```
> 
> Do you know of any specific problems with lower versions?
> 
> We got a large project using Django 1.6 unfortunately.. so I'll try to see if it works, but if you know of any specific problems it would be helpful
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lamby/django-slack/issues/42


-- 
Chris Lamb
chris-lamb.co.uk / @lolamby
