### ISSUE TITLE
Token should not be required if incoming webhook url is provided

### ISSUE THREAD

**Issue by giorgosp** [lamby/django-slack#48]
Hi, 

a token is not required if an endpoint url for an incoming webhook url is provided.
If you create an incoming webhook in slack, you will see that there is a curl example for this endpoint
which doesnt send a token. The webhook url is enough in this case.

**Comment by lamby** [comment]
Sorry, I don't follow. Can you give an example and/or link to those docs?

**Comment by giorgosp** [comment]
Yes, please take a look at https://api.slack.com/incoming-webhooks.
Check the "CURL EXAMPLE" section.

**Comment by lamby** [comment]
Thanks!
