### ISSUE TITLE
Django in requirements should be exactly defined

### ISSUE THREAD

**Issue by aleccool213** [lamby/django-slack#55]
## Summary

* All packages in the requirements should be defined by exact version number as packages which depend in this package will sometimes not be ready to upgrade
* More importantly, this package could sometimes break if a newer version of django comes out which is not compatible with the codebase

## Example:

* https://github.com/lamby/django-slack/blob/master/requirements.txt#L1 should be changed to `django==1.9.8` or `django==1.10.0`

**Comment by lamby** [comment]
Given that Django is mostly backwards compatible for a long time, I don't think is is a good idea at all. Especially as ``1.10.0`` is already superceded by a minor version number ``1.10.1`` where it works absolutely fine...
