### ISSUE TITLE
Wrong Subject for Error Messages

### ISSUE THREAD

**Issue by ShipraShalini** [lamby/django-slack#56]
Hi,

I am getting the Subject as 

> \u001b[31;1m\"POST /users/ HTTP/1.1\" 400 184\u001b[0m 

or the traceback for Slack handler whereas all other have correct Error messages.

How can I fix this?

**Comment by lamby** [comment]
I am lost - what error messages are these?

**Comment by lamby** [comment]
Ping?

**Comment by ShipraShalini** [comment]
Looks like it was some other error and I didn't get time to look into it.

I will again look into it by next month.

**Comment by lamby** [comment]
I'm going to close for now - re-open when you have more info :)
