### ISSUE TITLE
Clarification on how to obtain a production token

### ISSUE THREAD

**Issue by ataylor32** [lamby/django-slack#57]
During the development of my Django project, I've been using a test token from Slack, since that's what Slack says to do [here](https://api.slack.com/web#authentication) (emphasis mine):

> **While developing or testing your app**, you may use test tokens using our [test token generator](https://api.slack.com/docs/oauth-test-tokens).

It has been working fine. But now that I'm ready to go live with my Django project, I'm not sure what to do. I created a Slack app at https://api.slack.com/apps and saw that the app has a client ID and a client secret, but that doesn't seem like what I need for django-slack. Would you mind updating the documentation to clarify where to get a Slack token that's meant for production? Thank you!

**Comment by ataylor32** [comment]
I was able to find the right token by [creating a bot user](https://my.slack.com/services/new/bot). This might be a good addition to the django-slack documentation.

**Comment by lamby** [comment]
Ah the upstream docs have changed.… but given that you've *just* done this, I was wondering whether you would be position to the docs via a pull request? :3
