### ISSUE TITLE
RemovedInDjango20Warning: django.utils.functional.allow_lazy() is deprecated in favor of django.utils.functional.keep_lazy()

### ISSUE THREAD

**Issue by clokep** [lamby/django-slack#60]
I'm seeing the following on one of my projects running Django 1.10.5 with django-slack 5.7.1.

> /usr/local/venv/local/lib/python2.7/site-packages/django_slack/templatetags/django_slack.py:27:
> RemovedInDjango20Warning: django.utils.functional.allow_lazy() is deprecated in favor of django.utils.functional.keep_lazy()

Looking at [the docs](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.functional.allow_lazy) it looks like `allow_lazy` is only in 1.10, so probably just needs a:

```python
try:
    from django.utils.functional import keep_lazy as allow_lazy
except ImportError
    from django.utils.functional import allow_lazy
```

**Comment by lamby** [comment]
Thanks!

**Comment by thomwiggers** [comment]
This introduced a syntax error, see PR #61

**Comment by clokep** [comment]
Thanks for fixing this! 👍
