### ISSUE TITLE
Django is unable to initialize when slack.com is not available

### ISSUE THREAD

**Issue by manbehindthemadness** [lamby/django-slack#62]
Django is unable to initialize when slack.com is not available or when the target channel is missing.
Suggest that a failure in the API key, or other environmental problems will post errors into the django log whilst still allowing the system to load and function without.

**Comment by manbehindthemadness** [comment]
I have solved the problem by implementing a warning wrapper
[revisions.zip](https://github.com/lamby/django-slack/files/719699/revisions.zip)

**Comment by lamby** [comment]
I'm sorry but I have no idea what these changes are proposing. Please use the pull request mechanism and try and minimise your changes as much as possible.

**Comment by lamby** [comment]
(Closing issue as "more info needed")
