### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by clokep** [lamby/django-slack#64]
First, thanks for making this package! 👍 

I appreciate that you push new releases quickly after merging PRs, but is there a changelog available? It's hard to tell how big of a change was made between versions without seeing a list of changes somewhere.

Sorry if it's available somewhere already and I missed it! Thanks.

**Comment by lamby** [comment]
Ah, unfortunately I do not have one beyond Git. I will create one in future... thanks :)

**Comment by denizdogan** [comment]
@lamby Maybe it's time to revisit this one? :) I'm on 5.10.2 and I'm not sure if 5.13.0 contains bug fixes, breaking changes, etc.

**Comment by lamby** [comment]
You can tell from the semver version name, no? :)
