### ISSUE TITLE
No (obvious) way to test messages

### ISSUE THREAD

**Issue by inglesp** [lamby/django-slack#67]
As far as I can see, the only way to test that a message has been sent is through mocking.

Would you accept a patch that added a backend that looked like this?

```
class TestBackend(Backend):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.reset_messages()

    def send(self, url, data, **kwargs):
        self.messages.append(data)

    def reset_messages(self):
        self.messages = []

    def retrieve_messages(self):
        messages = self.messages
        self.reset_messages()
        return messages
```

This could be used in more-or-less the same way as Django's `core.mail.backends.locmem.EmailBackend`, with the proviso that you need to manually call `.reset_messages()` on the backend before testing that something has sent a message.

**Comment by lamby** [comment]
> Would you accept a patch that added a backend that looked like this?

Absolutely. Please send it over :)
