### ISSUE TITLE
Docs not rendering correctly on readthedocs.io

### ISSUE THREAD

**Issue by feakuru** [lamby/django-slack#69]
Hi! For the last few days, whenever I open http://django-slack.readthedocs.io, I get no CSS or JS on the page and am thus unable to navigate the docs properly.

**Comment by feakuru** [comment]
[screenshot](https://ibb.co/iS5OVQ)

**Comment by lamby** [comment]
Hm. I can't seem to work out why this is. See:

https://readthedocs.org/projects/django-slack/builds/5650583/

I just committed https://github.com/lamby/django-slack/commit/8087d215ac08cded2af214a3452fdaa4d685e76e but I don't think it will help.

**Comment by feakuru** [comment]
https://github.com/sphinx-doc/sphinx/issues/2633
https://github.com/rst2pdf/rst2pdf/issues/568
https://github.com/python-babel/babel/issues/56
These seem related. Might help to have a look

**Comment by lamby** [comment]
> These seem related. Might help to have a look

Thanks, although I can't quite see how I can change *my* docs to prevent this issue - the linked issues seem to be about ways of fixing Sphinx itself? I'm probably missing something obvious...

**Comment by SimonBarendse** [comment]
Seems like the toctree_only argument is missing from the latex_documents in the sphinx conf.

See: http://www.sphinx-doc.org/en/stable/config.html#confval-latex_documents

I've opened #74 to fix this.

**Comment by lamby** [comment]
\o/

**Comment by SimonBarendse** [comment]
Missed something: we also need the auhtor to be set.
I've opened another PR to fix this.

**Comment by SimonBarendse** [comment]
Build is passing now, but we still need #76 to get the theme back.
