### ISSUE TITLE
TestBackend init does not support python 2.7

### ISSUE THREAD

**Issue by jheld** [lamby/django-slack#72]
The __init__ of `TestBackend` uses 0 arguments to the call to `super`; unfortunately python2.7 does not support this.

**Comment by lamby** [comment]
Was added in https://github.com/lamby/django-slack/commit/b55f9621313ce30b95b9435b3b749f9a94d518cb#diff-b37b5e3c61ba2f217064f8a17362a9faR82

@inglesp Can you take a quick look? :)

**Comment by lamby** [comment]
Thanks all!

Released upon PyPI as ``5.10.2``
