### ISSUE TITLE
Unable to get the response of Slack API

### ISSUE THREAD

**Issue by hexchain** [lamby/django-slack#82]
Currently, django-slack does not provide the response of the Slack API, making it impossible to update a sent message afterwards (which requires the `ts` value from the response).

Is this specially designed so, or just a missing feature?

**Comment by hexchain** [comment]
It seems that it is not easy to provide the return value consistently - some backends are dummy ones that do not return, some are asynchronous that cannot provide API response immediately.

**Comment by lamby** [comment]
@hexchain wrote:

> some are asynchronous that cannot provide API response immediately.

Indeed. However, the synchronous ones should and could definitely use this. Can you provide a patch? :)

**Comment by hexchain** [comment]
The response can still be provided for the Celery backend if result storage is configured for celery, but that would introduce another return type for `send_message`.

**Comment by lamby** [comment]
Released as `5.12.0` — thank you.
